server:
    port: 8000

spring:
    application:
        name: COVID-19
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/covid19_db?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
        driver-class: com.mysql.cj.jdbc.Driver
    idhs:
        url: http://43.224.124.234:7080/api
        username: dev
        password: Dev1234#
    pid:
        file: application.pid
    portal:
        userCredentials:
            - [dev1@aaa.com, dev]
            - [dev2@aaa.com, dev]
    googleapi:
        mapKey: abc

firebase: 
    configurations:
        path: credentials/covid-19-lk-dev-firebase-adminsdk.json
    notifications:
       topic: 'mobile_message'
       title: 'Common topic - Hello'
       message: 'Sending test message'
       token: ''
       payloadMessageId: '123'
       payloadData: 'Hello. This is payload content.'
